export * from './range';
export { default as assertIterable } from './assertIterable';
export { default as compact } from './compact';
export { default as compose } from './compose';
export { default as filter } from './filter';
export { default as getArray } from './getArray';
export { default as getIterator } from './getIterator';
export { default as isIterable } from './isIterable';
export { default as map } from './map';
export { default as memoize } from './memoize';
export { default as pluck } from './pluck';
export { default as slice } from './slice';
export { default as tail } from './tail';
export { default as take } from './take';
export { default as unique } from './unique';
export { default as zipWith } from './zipWith';
